from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadCefalogramas(object):
    def setupUi(self, CadCefalogramas):
        CadCefalogramas.setObjectName("CadCefalogramas")
        CadCefalogramas.setWindowModality(QtCore.Qt.WindowModal)
        CadCefalogramas.resize(684, 501)
        self.centralwidget = QtWidgets.QWidget(CadCefalogramas)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.edtId = QtWidgets.QLineEdit(self.centralwidget)
        self.edtId.setObjectName("edtId")
        self.verticalLayout.addWidget(self.edtId)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edtPaciente = QtWidgets.QLineEdit(self.centralwidget)
        self.edtPaciente.setEnabled(False)
        self.edtPaciente.setObjectName("edtPaciente")
        self.horizontalLayout_2.addWidget(self.edtPaciente)
        self.btnLimparPaciente = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimparPaciente.setEnabled(False)
        self.btnLimparPaciente.setObjectName("btnLimparPaciente")
        self.horizontalLayout_2.addWidget(self.btnLimparPaciente)
        self.btnPesqPaciente = QtWidgets.QPushButton(self.centralwidget)
        self.btnPesqPaciente.setEnabled(False)
        self.btnPesqPaciente.setObjectName("btnPesqPaciente")
        self.horizontalLayout_2.addWidget(self.btnPesqPaciente)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edtAluno = QtWidgets.QLineEdit(self.centralwidget)
        self.edtAluno.setEnabled(False)
        self.edtAluno.setObjectName("edtAluno")
        self.horizontalLayout_3.addWidget(self.edtAluno)
        self.btnLimparAluno = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimparAluno.setEnabled(False)
        self.btnLimparAluno.setObjectName("btnLimparAluno")
        self.horizontalLayout_3.addWidget(self.btnLimparAluno)
        self.btnPesqAluno = QtWidgets.QPushButton(self.centralwidget)
        self.btnPesqAluno.setEnabled(False)
        self.btnPesqAluno.setObjectName("btnPesqAluno")
        self.horizontalLayout_3.addWidget(self.btnPesqAluno)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.edtValor = QtWidgets.QLineEdit(self.centralwidget)
        self.edtValor.setEnabled(False)
        self.edtValor.setObjectName("edtValor")
        self.verticalLayout.addWidget(self.edtValor)
        self.chkEntregue = QtWidgets.QCheckBox(self.centralwidget)
        self.chkEntregue.setEnabled(False)
        self.chkEntregue.setObjectName("chkEntregue")
        self.verticalLayout.addWidget(self.chkEntregue)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.edtEntrega = QtWidgets.QDateEdit(self.centralwidget)
        self.edtEntrega.setEnabled(False)
        self.edtEntrega.setObjectName("edtEntrega")
        self.verticalLayout.addWidget(self.edtEntrega)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.edtMotivo = QtWidgets.QLineEdit(self.centralwidget)
        self.edtMotivo.setEnabled(False)
        self.edtMotivo.setObjectName("edtMotivo")
        self.verticalLayout.addWidget(self.edtMotivo)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.cboModelo = QtWidgets.QComboBox(self.centralwidget)
        self.cboModelo.setEnabled(False)
        self.cboModelo.setObjectName("cboModelo")
        self.cboModelo.addItem("")
        self.cboModelo.addItem("")
        self.cboModelo.addItem("")
        self.cboModelo.addItem("")
        self.verticalLayout.addWidget(self.cboModelo)
        self.btnParametrizacao = QtWidgets.QPushButton(self.centralwidget)
        self.btnParametrizacao.setEnabled(False)
        self.btnParametrizacao.setObjectName("btnParametrizacao")
        self.verticalLayout.addWidget(self.btnParametrizacao)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnNovo = QtWidgets.QPushButton(self.centralwidget)
        self.btnNovo.setObjectName("btnNovo")
        self.verticalLayout_2.addWidget(self.btnNovo)
        self.btnSalvar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setObjectName("btnSalvar")
        self.verticalLayout_2.addWidget(self.btnSalvar)
        self.btnPesquisar = QtWidgets.QPushButton(self.centralwidget)
        self.btnPesquisar.setObjectName("btnPesquisar")
        self.verticalLayout_2.addWidget(self.btnPesquisar)
        self.btnRemover = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemover.setEnabled(False)
        self.btnRemover.setObjectName("btnRemover")
        self.verticalLayout_2.addWidget(self.btnRemover)
        self.btnSair = QtWidgets.QPushButton(self.centralwidget)
        self.btnSair.setObjectName("btnSair")
        self.verticalLayout_2.addWidget(self.btnSair)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        CadCefalogramas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CadCefalogramas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 22))
        self.menubar.setObjectName("menubar")
        CadCefalogramas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CadCefalogramas)
        self.statusbar.setObjectName("statusbar")
        CadCefalogramas.setStatusBar(self.statusbar)

        self.retranslateUi(CadCefalogramas)
        QtCore.QMetaObject.connectSlotsByName(CadCefalogramas)

    def retranslateUi(self, CadCefalogramas):
        _translate = QtCore.QCoreApplication.translate
        CadCefalogramas.setWindowTitle(_translate("CadCefalogramas", "Cefalogramas"))
        self.label_2.setText(_translate("CadCefalogramas", "Id"))
        self.label.setText(_translate("CadCefalogramas", "Paciente"))
        self.btnLimparPaciente.setText(_translate("CadCefalogramas", "Limpar"))
        self.btnPesqPaciente.setText(_translate("CadCefalogramas", "Pesquisar"))
        self.label_3.setText(_translate("CadCefalogramas", "Aluno"))
        self.btnLimparAluno.setText(_translate("CadCefalogramas", "Limpar"))
        self.btnPesqAluno.setText(_translate("CadCefalogramas", "Pesquisar"))
        self.label_4.setText(_translate("CadCefalogramas", "Valor"))
        self.chkEntregue.setText(_translate("CadCefalogramas", "Entregue"))
        self.label_7.setText(_translate("CadCefalogramas", "Data de Entrega"))
        self.label_6.setText(_translate("CadCefalogramas", "Motivo"))
        self.label_5.setText(_translate("CadCefalogramas", "Modelo"))
        self.cboModelo.setItemText(0, _translate("CadCefalogramas", "Modelo 1"))
        self.cboModelo.setItemText(1, _translate("CadCefalogramas", "Modelo 2"))
        self.cboModelo.setItemText(2, _translate("CadCefalogramas", "Modelo 3"))
        self.cboModelo.setItemText(3, _translate("CadCefalogramas", "Modelo 4"))
        self.btnParametrizacao.setText(_translate("CadCefalogramas", "Parametrização"))
        self.btnNovo.setText(_translate("CadCefalogramas", "&Novo"))
        self.btnSalvar.setText(_translate("CadCefalogramas", "&Salvar"))
        self.btnPesquisar.setText(_translate("CadCefalogramas", "&Pesquisar"))
        self.btnRemover.setText(_translate("CadCefalogramas", "&Remover"))
        self.btnSair.setText(_translate("CadCefalogramas", "Sai&r"))


    def set_mode(self, edit=True):
        self.edtId.setEnabled(not edit)
        self.btnPesqPaciente.setEnabled(edit)
        self.btnLimparPaciente.setEnabled(edit)
        self.btnPesqAluno.setEnabled(edit)
        self.btnLimparAluno.setEnabled(edit)
        self.edtValor.setEnabled(edit)
        self.cbEntregue.setEnabled(edit)
        self.edtEntrega.setEnabled(edit)
        self.edtMotivo.setEnabled(edit)
        self.cboModelo.setEnabled(edit)
        self.btnParametrizacao.setEnabled(edit)

        self.btnNovo.setEnabled(not edit)
        self.btnSalvar.setEnabled(edit)
        self.btnPesquisar.setEnabled(not edit)
        self.btnRemover.setEnabled(edit)
        self.btnSair.setEnabled(not edit)