from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadPanoramicas(object):
    def setupUi(self, CadPanoramicas):
        CadPanoramicas.setObjectName("CadPanoramicas")
        CadPanoramicas.setWindowModality(QtCore.Qt.WindowModal)
        CadPanoramicas.resize(1009, 663)
        self.centralwidget = QtWidgets.QWidget(CadPanoramicas)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.edtId = QtWidgets.QLineEdit(self.centralwidget)
        self.edtId.setObjectName("edtId")
        self.verticalLayout.addWidget(self.edtId)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edtPaciente = QtWidgets.QLineEdit(self.centralwidget)
        self.edtPaciente.setEnabled(False)
        self.edtPaciente.setObjectName("edtPaciente")
        self.horizontalLayout.addWidget(self.edtPaciente)
        self.btnLimparPaciente = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimparPaciente.setEnabled(False)
        self.btnLimparPaciente.setObjectName("btnLimparPaciente")
        self.horizontalLayout.addWidget(self.btnLimparPaciente)
        self.btnPesqPaciente = QtWidgets.QPushButton(self.centralwidget)
        self.btnPesqPaciente.setEnabled(False)
        self.btnPesqPaciente.setObjectName("btnPesqPaciente")
        self.horizontalLayout.addWidget(self.btnPesqPaciente)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edtAluno = QtWidgets.QLineEdit(self.centralwidget)
        self.edtAluno.setEnabled(False)
        self.edtAluno.setObjectName("edtAluno")
        self.horizontalLayout_3.addWidget(self.edtAluno)
        self.btnLimparAluno = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimparAluno.setEnabled(False)
        self.btnLimparAluno.setObjectName("btnLimparAluno")
        self.horizontalLayout_3.addWidget(self.btnLimparAluno)
        self.btnPesqAluno = QtWidgets.QPushButton(self.centralwidget)
        self.btnPesqAluno.setEnabled(False)
        self.btnPesqAluno.setObjectName("btnPesqAluno")
        self.horizontalLayout_3.addWidget(self.btnPesqAluno)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.edtValor = QtWidgets.QLineEdit(self.centralwidget)
        self.edtValor.setEnabled(False)
        self.edtValor.setObjectName("edtValor")
        self.verticalLayout.addWidget(self.edtValor)
        self.cbEntregue = QtWidgets.QCheckBox(self.centralwidget)
        self.cbEntregue.setEnabled(False)
        self.cbEntregue.setObjectName("cbEntregue")
        self.verticalLayout.addWidget(self.cbEntregue)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.edtEntrega = QtWidgets.QDateEdit(self.centralwidget)
        self.edtEntrega.setEnabled(False)
        self.edtEntrega.setObjectName("edtEntrega")
        self.verticalLayout.addWidget(self.edtEntrega)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.edtMotivo = QtWidgets.QLineEdit(self.centralwidget)
        self.edtMotivo.setEnabled(False)
        self.edtMotivo.setObjectName("edtMotivo")
        self.verticalLayout.addWidget(self.edtMotivo)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.cboTipo = QtWidgets.QComboBox(self.centralwidget)
        self.cboTipo.setEnabled(False)
        self.cboTipo.setObjectName("cboTipo")
        self.cboTipo.addItem("")
        self.cboTipo.addItem("")
        self.cboTipo.addItem("")
        self.cboTipo.addItem("")
        self.cboTipo.addItem("")
        self.cboTipo.addItem("")
        self.cboTipo.addItem("")
        self.cboTipo.addItem("")
        self.verticalLayout.addWidget(self.cboTipo)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.cboEspecializacao = QtWidgets.QComboBox(self.centralwidget)
        self.cboEspecializacao.setEnabled(False)
        self.cboEspecializacao.setObjectName("cboEspecializacao")
        self.cboEspecializacao.addItem("")
        self.cboEspecializacao.addItem("")
        self.cboEspecializacao.addItem("")
        self.cboEspecializacao.addItem("")
        self.verticalLayout.addWidget(self.cboEspecializacao)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.edtRegiao = QtWidgets.QLineEdit(self.centralwidget)
        self.edtRegiao.setEnabled(False)
        self.edtRegiao.setObjectName("edtRegiao")
        self.verticalLayout.addWidget(self.edtRegiao)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.cboModelo = QtWidgets.QComboBox(self.centralwidget)
        self.cboModelo.setEnabled(False)
        self.cboModelo.setObjectName("cboModelo")
        self.cboModelo.addItem("")
        self.cboModelo.addItem("")
        self.cboModelo.addItem("")
        self.cboModelo.addItem("")
        self.cboModelo.addItem("")
        self.cboModelo.addItem("")
        self.cboModelo.addItem("")
        self.cboModelo.addItem("")
        self.cboModelo.addItem("")
        self.verticalLayout.addWidget(self.cboModelo)
        self.btnParametrizacao = QtWidgets.QPushButton(self.centralwidget)
        self.btnParametrizacao.setEnabled(False)
        self.btnParametrizacao.setObjectName("btnParametrizacao")
        self.verticalLayout.addWidget(self.btnParametrizacao)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnNovo = QtWidgets.QPushButton(self.centralwidget)
        self.btnNovo.setObjectName("btnNovo")
        self.verticalLayout_2.addWidget(self.btnNovo)
        self.btnSalvar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setObjectName("btnSalvar")
        self.verticalLayout_2.addWidget(self.btnSalvar)
        self.btnPesquisar = QtWidgets.QPushButton(self.centralwidget)
        self.btnPesquisar.setObjectName("btnPesquisar")
        self.verticalLayout_2.addWidget(self.btnPesquisar)
        self.btnRemover = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemover.setEnabled(False)
        self.btnRemover.setObjectName("btnRemover")
        self.verticalLayout_2.addWidget(self.btnRemover)
        self.btnSair = QtWidgets.QPushButton(self.centralwidget)
        self.btnSair.setObjectName("btnSair")
        self.verticalLayout_2.addWidget(self.btnSair)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        CadPanoramicas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CadPanoramicas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1009, 22))
        self.menubar.setObjectName("menubar")
        CadPanoramicas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CadPanoramicas)
        self.statusbar.setObjectName("statusbar")
        CadPanoramicas.setStatusBar(self.statusbar)

        self.retranslateUi(CadPanoramicas)
        QtCore.QMetaObject.connectSlotsByName(CadPanoramicas)

    def retranslateUi(self, CadPanoramicas):
        _translate = QtCore.QCoreApplication.translate
        CadPanoramicas.setWindowTitle(_translate("CadPanoramicas", "Panoramicas"))
        self.label.setText(_translate("CadPanoramicas", "Id"))
        self.label_2.setText(_translate("CadPanoramicas", "Paciente"))
        self.btnLimparPaciente.setText(_translate("CadPanoramicas", "Limpar"))
        self.btnPesqPaciente.setText(_translate("CadPanoramicas", "Pesquisar"))
        self.label_3.setText(_translate("CadPanoramicas", "Aluno"))
        self.btnLimparAluno.setText(_translate("CadPanoramicas", "Limpar"))
        self.btnPesqAluno.setText(_translate("CadPanoramicas", "Pesquisar"))
        self.label_4.setText(_translate("CadPanoramicas", "Valor"))
        self.cbEntregue.setText(_translate("CadPanoramicas", "Entregue"))
        self.label_5.setText(_translate("CadPanoramicas", "Data de Entrega"))
        self.label_6.setText(_translate("CadPanoramicas", "Motivo"))
        self.label_7.setText(_translate("CadPanoramicas", "Tipo"))
        self.cboTipo.setItemText(0, _translate("CadPanoramicas", "Normal"))
        self.cboTipo.setItemText(1, _translate("CadPanoramicas", "Infantil"))
        self.cboTipo.setItemText(2, _translate("CadPanoramicas", "Implantes"))
        self.cboTipo.setItemText(3, _translate("CadPanoramicas", "Telerradiografia Lateral"))
        self.cboTipo.setItemText(4, _translate("CadPanoramicas", "Telerradiografia Frontal"))
        self.cboTipo.setItemText(5, _translate("CadPanoramicas", "Radiografia Carpal"))
        self.cboTipo.setItemText(6, _translate("CadPanoramicas", "Radiografia Atm Planigrafia"))
        self.cboTipo.setItemText(7, _translate("CadPanoramicas", "Radiografia Seios Maxilares"))
        self.label_8.setText(_translate("CadPanoramicas", "Especialização"))
        self.cboEspecializacao.setItemText(0, _translate("CadPanoramicas", "Nenhuma"))
        self.cboEspecializacao.setItemText(1, _translate("CadPanoramicas", "Topo"))
        self.cboEspecializacao.setItemText(2, _translate("CadPanoramicas", "Oclusao"))
        self.cboEspecializacao.setItemText(3, _translate("CadPanoramicas", "Idade Ossea"))
        self.label_9.setText(_translate("CadPanoramicas", "Região"))
        self.label_10.setText(_translate("CadPanoramicas", "Modelo"))
        self.cboModelo.setItemText(0, _translate("CadPanoramicas", "Modelo 1"))
        self.cboModelo.setItemText(1, _translate("CadPanoramicas", "Modelo 2"))
        self.cboModelo.setItemText(2, _translate("CadPanoramicas", "Modelo 3"))
        self.cboModelo.setItemText(3, _translate("CadPanoramicas", "Modelo 4"))
        self.cboModelo.setItemText(4, _translate("CadPanoramicas", "Modelo 5"))
        self.cboModelo.setItemText(5, _translate("CadPanoramicas", "Modelo 6"))
        self.cboModelo.setItemText(6, _translate("CadPanoramicas", "Modelo 7"))
        self.cboModelo.setItemText(7, _translate("CadPanoramicas", "Modelo 8"))
        self.cboModelo.setItemText(8, _translate("CadPanoramicas", "Modelo 9"))
        self.btnParametrizacao.setText(_translate("CadPanoramicas", "Parametrização"))
        self.btnNovo.setText(_translate("CadPanoramicas", "&Novo"))
        self.btnSalvar.setText(_translate("CadPanoramicas", "&Salvar"))
        self.btnPesquisar.setText(_translate("CadPanoramicas", "&Pesquisar"))
        self.btnRemover.setText(_translate("CadPanoramicas", "&Remover"))
        self.btnSair.setText(_translate("CadPanoramicas", "Sai&r"))


    def set_mode(self, edit=True):
        self.edtId.setEnabled(not edit)
        self.btnPesqPaciente.setEnabled(edit)
        self.btnLimparPaciente.setEnabled(edit)
        self.btnPesqAluno.setEnabled(edit)
        self.btnLimparAluno.setEnabled(edit)
        self.edtValor.setEnabled(edit)
        self.cbEntregue.setEnabled(edit)
        self.edtEntrega.setEnabled(edit)
        self.edtMotivo.setEnabled(edit)
        self.cboTipo.setEnabled(edit)
        self.cboEspecializacao.setEnabled(edit)
        self.edtRegiao.setEnabled(edit)
        self.cboModelo.setEnabled(edit)
        self.btnParametrizacao.setEnabled(edit)

        self.btnNovo.setEnabled(not edit)
        self.btnSalvar.setEnabled(edit)
        self.btnPesquisar.setEnabled(not edit)
        self.btnRemover.setEnabled(edit)
        self.btnSair.setEnabled(not edit)