from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadPacientes(object):
    def setupUi(self, CadPacientes):
        CadPacientes.setObjectName("CadPacientes")
        CadPacientes.resize(424, 331)
        self.centralwidget = QtWidgets.QWidget(CadPacientes)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.edtId = QtWidgets.QLineEdit(self.centralwidget)
        self.edtId.setObjectName("edtId")
        self.verticalLayout.addWidget(self.edtId)
        self.lblNome = QtWidgets.QLabel(self.centralwidget)
        self.lblNome.setObjectName("lblNome")
        self.verticalLayout.addWidget(self.lblNome)
        self.edtNome = QtWidgets.QLineEdit(self.centralwidget)
        self.edtNome.setEnabled(False)
        self.edtNome.setObjectName("edtNome")
        self.verticalLayout.addWidget(self.edtNome)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.edtNasc = QtWidgets.QDateEdit(self.centralwidget)
        self.edtNasc.setEnabled(False)
        self.edtNasc.setObjectName("edtNasc")
        self.verticalLayout.addWidget(self.edtNasc)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.edtClinViewId = QtWidgets.QLineEdit(self.centralwidget)
        self.edtClinViewId.setEnabled(False)
        self.edtClinViewId.setObjectName("edtClinViewId")
        self.verticalLayout.addWidget(self.edtClinViewId)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edtIndicacao = QtWidgets.QLineEdit(self.centralwidget)
        self.edtIndicacao.setEnabled(False)
        self.edtIndicacao.setObjectName("edtIndicacao")
        self.horizontalLayout_2.addWidget(self.edtIndicacao)
        self.btnPesqIndicacao = QtWidgets.QPushButton(self.centralwidget)
        self.btnPesqIndicacao.setEnabled(False)
        self.btnPesqIndicacao.setObjectName("btnPesqIndicacao")
        self.horizontalLayout_2.addWidget(self.btnPesqIndicacao)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnNovo = QtWidgets.QPushButton(self.centralwidget)
        self.btnNovo.setObjectName("btnNovo")
        self.verticalLayout_2.addWidget(self.btnNovo)
        self.btnSalvar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setObjectName("btnSalvar")
        self.verticalLayout_2.addWidget(self.btnSalvar)
        self.btnPesquisar = QtWidgets.QPushButton(self.centralwidget)
        self.btnPesquisar.setObjectName("btnPesquisar")
        self.verticalLayout_2.addWidget(self.btnPesquisar)
        self.btnRemover = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemover.setEnabled(False)
        self.btnRemover.setObjectName("btnRemover")
        self.verticalLayout_2.addWidget(self.btnRemover)
        self.btnSair = QtWidgets.QPushButton(self.centralwidget)
        self.btnSair.setObjectName("btnSair")
        self.verticalLayout_2.addWidget(self.btnSair)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        CadPacientes.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CadPacientes)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 424, 22))
        self.menubar.setObjectName("menubar")
        CadPacientes.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CadPacientes)
        self.statusbar.setObjectName("statusbar")
        CadPacientes.setStatusBar(self.statusbar)

        self.retranslateUi(CadPacientes)
        QtCore.QMetaObject.connectSlotsByName(CadPacientes)

    def retranslateUi(self, CadPacientes):
        _translate = QtCore.QCoreApplication.translate
        CadPacientes.setWindowTitle(_translate("CadPacientes", "Pacientes"))
        self.label_4.setText(_translate("CadPacientes", "Id"))
        self.lblNome.setText(_translate("CadPacientes", "Nome"))
        self.label_3.setText(_translate("CadPacientes", "Data de Nascimento"))
        self.label.setText(_translate("CadPacientes", "ClinView Id"))
        self.label_2.setText(_translate("CadPacientes", "Indicação"))
        self.btnPesqIndicacao.setText(_translate("CadPacientes", "Pesquisar"))
        self.btnNovo.setText(_translate("CadPacientes", "&Novo"))
        self.btnSalvar.setText(_translate("CadPacientes", "&Salvar"))
        self.btnPesquisar.setText(_translate("CadPacientes", "&Pesquisar"))
        self.btnRemover.setText(_translate("CadPacientes", "&Remover"))
        self.btnSair.setText(_translate("CadPacientes", "Sai&r"))

    def set_mode(self, edit=True):
        self.edtId.setEnabled(not edit)
        self.edtNome.setEnabled(edit)
        self.edtNasc.setEnabled(edit)
        self.edtClinViewId.setEnabled(edit)
        self.btnPesqIndicacao.setEnabled(edit)

        self.btnNovo.setEnabled(not edit)
        self.btnSalvar.setEnabled(edit)
        self.btnPesquisar.setEnabled(not edit)
        self.btnRemover.setEnabled(edit)
        self.btnSair.setEnabled(not edit)