from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadParametrizacoes(object):
    def setupUi(self, CadParametrizacoes):
        CadParametrizacoes.setObjectName("CadParametrizacoes")
        CadParametrizacoes.setWindowModality(QtCore.Qt.WindowModal)
        CadParametrizacoes.resize(575, 284)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CadParametrizacoes)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(CadParametrizacoes)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.edtTensao = QtWidgets.QLineEdit(CadParametrizacoes)
        self.edtTensao.setObjectName("edtTensao")
        self.verticalLayout.addWidget(self.edtTensao)
        self.label_2 = QtWidgets.QLabel(CadParametrizacoes)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.edtCorrente = QtWidgets.QLineEdit(CadParametrizacoes)
        self.edtCorrente.setObjectName("edtCorrente")
        self.verticalLayout.addWidget(self.edtCorrente)
        self.label_3 = QtWidgets.QLabel(CadParametrizacoes)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.edtTempo = QtWidgets.QLineEdit(CadParametrizacoes)
        self.edtTempo.setObjectName("edtTempo")
        self.verticalLayout.addWidget(self.edtTempo)
        self.label_4 = QtWidgets.QLabel(CadParametrizacoes)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.edtMgycm = QtWidgets.QLineEdit(CadParametrizacoes)
        self.edtMgycm.setObjectName("edtMgycm")
        self.verticalLayout.addWidget(self.edtMgycm)
        self.label_5 = QtWidgets.QLabel(CadParametrizacoes)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.cboTamanho = QtWidgets.QComboBox(CadParametrizacoes)
        self.cboTamanho.setObjectName("cboTamanho")
        self.cboTamanho.addItem("")
        self.cboTamanho.addItem("")
        self.cboTamanho.addItem("")
        self.cboTamanho.addItem("")
        self.verticalLayout.addWidget(self.cboTamanho)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnSalvar = QtWidgets.QPushButton(CadParametrizacoes)
        self.btnSalvar.setObjectName("btnSalvar")
        self.verticalLayout_2.addWidget(self.btnSalvar)
        self.btnCancelar = QtWidgets.QPushButton(CadParametrizacoes)
        self.btnCancelar.setObjectName("btnCancelar")
        self.verticalLayout_2.addWidget(self.btnCancelar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(CadParametrizacoes)
        QtCore.QMetaObject.connectSlotsByName(CadParametrizacoes)

    def retranslateUi(self, CadParametrizacoes):
        _translate = QtCore.QCoreApplication.translate
        CadParametrizacoes.setWindowTitle(_translate("CadParametrizacoes", "Parametrização"))
        self.label.setText(_translate("CadParametrizacoes", "Tensão"))
        self.label_2.setText(_translate("CadParametrizacoes", "Corrente"))
        self.label_3.setText(_translate("CadParametrizacoes", "Tempo"))
        self.label_4.setText(_translate("CadParametrizacoes", "mGycm"))
        self.label_5.setText(_translate("CadParametrizacoes", "Tamanho"))
        self.cboTamanho.setItemText(0, _translate("CadParametrizacoes", "Pequeno"))
        self.cboTamanho.setItemText(1, _translate("CadParametrizacoes", "Médio"))
        self.cboTamanho.setItemText(2, _translate("CadParametrizacoes", "Grande"))
        self.cboTamanho.setItemText(3, _translate("CadParametrizacoes", "Extra Grande"))
        self.btnSalvar.setText(_translate("CadParametrizacoes", "&Salvar"))
        self.btnCancelar.setText(_translate("CadParametrizacoes", "&Cancelar"))