from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuCadastros = QtWidgets.QMenu(self.menubar)
        self.menuCadastros.setObjectName("menuCadastros")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionIndica_es = QtWidgets.QAction(MainWindow)
        self.actionIndica_es.setObjectName("actionIndica_es")
        self.actionAlunos = QtWidgets.QAction(MainWindow)
        self.actionAlunos.setObjectName("actionAlunos")
        self.actionPacientes = QtWidgets.QAction(MainWindow)
        self.actionPacientes.setObjectName("actionPacientes")
        self.actionPanoramicas = QtWidgets.QAction(MainWindow)
        self.actionPanoramicas.setObjectName("actionPanoramicas")
        self.actionTomografias = QtWidgets.QAction(MainWindow)
        self.actionTomografias.setObjectName("actionTomografias")
        self.actionCefalogramas = QtWidgets.QAction(MainWindow)
        self.actionCefalogramas.setObjectName("actionCefalogramas")
        self.menuCadastros.addAction(self.actionIndica_es)
        self.menuCadastros.addAction(self.actionAlunos)
        self.menuCadastros.addAction(self.actionPacientes)
        self.menuCadastros.addAction(self.actionPanoramicas)
        self.menuCadastros.addAction(self.actionTomografias)
        self.menuCadastros.addAction(self.actionCefalogramas)
        self.menubar.addAction(self.menuCadastros.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Odonto"))
        self.menuCadastros.setTitle(_translate("MainWindow", "Cadastros"))
        self.actionIndica_es.setText(_translate("MainWindow", "Indicações"))
        self.actionAlunos.setText(_translate("MainWindow", "Alunos"))
        self.actionPacientes.setText(_translate("MainWindow", "Pacientes"))
        self.actionPanoramicas.setText(_translate("MainWindow", "Panorâmicas"))
        self.actionTomografias.setText(_translate("MainWindow", "Tomografias"))
        self.actionCefalogramas.setText(_translate("MainWindow", "Cefalogramas"))