from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PeqPacientes(object):
    def setupUi(self, PeqPacientes):
        PeqPacientes.setObjectName("PeqPacientes")
        PeqPacientes.resize(628, 546)
        self.verticalLayout = QtWidgets.QVBoxLayout(PeqPacientes)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(PeqPacientes)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.edtNome = QtWidgets.QLineEdit(PeqPacientes)
        self.edtNome.setObjectName("edtNome")
        self.verticalLayout.addWidget(self.edtNome)
        self.label_3 = QtWidgets.QLabel(PeqPacientes)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.edtClinViewId = QtWidgets.QLineEdit(PeqPacientes)
        self.edtClinViewId.setObjectName("edtClinViewId")
        self.verticalLayout.addWidget(self.edtClinViewId)
        self.label_2 = QtWidgets.QLabel(PeqPacientes)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edtIndicacao = QtWidgets.QLineEdit(PeqPacientes)
        self.edtIndicacao.setEnabled(False)
        self.edtIndicacao.setObjectName("edtIndicacao")
        self.horizontalLayout.addWidget(self.edtIndicacao)
        self.btnPesqIndicacao = QtWidgets.QPushButton(PeqPacientes)
        self.btnPesqIndicacao.setObjectName("btnPesqIndicacao")
        self.horizontalLayout.addWidget(self.btnPesqIndicacao)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(PeqPacientes)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.btnConfirmar = QtWidgets.QPushButton(PeqPacientes)
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.verticalLayout.addWidget(self.btnConfirmar)
        self.btnCancelar = QtWidgets.QPushButton(PeqPacientes)
        self.btnCancelar.setObjectName("btnCancelar")
        self.verticalLayout.addWidget(self.btnCancelar)

        self.retranslateUi(PeqPacientes)
        QtCore.QMetaObject.connectSlotsByName(PeqPacientes)

    def retranslateUi(self, PeqPacientes):
        _translate = QtCore.QCoreApplication.translate
        PeqPacientes.setWindowTitle(_translate("PeqPacientes", "Dialog"))
        self.label.setText(_translate("PeqPacientes", "Nome"))
        self.label_3.setText(_translate("PeqPacientes", "ClinView Id"))
        self.label_2.setText(_translate("PeqPacientes", "Indicação"))
        self.btnPesqIndicacao.setText(_translate("PeqPacientes", "Pesquisar"))
        self.btnConfirmar.setText(_translate("PeqPacientes", "&Confirmar"))
        self.btnCancelar.setText(_translate("PeqPacientes", "Cancela&r"))
