from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PesqTomografias(object):
    def setupUi(self, PesqTomografias):
        PesqTomografias.setObjectName("PesqTomografias")
        PesqTomografias.resize(582, 473)
        self.verticalLayout = QtWidgets.QVBoxLayout(PesqTomografias)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(PesqTomografias)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edtPaciente = QtWidgets.QLineEdit(PesqTomografias)
        self.edtPaciente.setEnabled(False)
        self.edtPaciente.setObjectName("edtPaciente")
        self.horizontalLayout.addWidget(self.edtPaciente)
        self.btnLimparPaciente = QtWidgets.QPushButton(PesqTomografias)
        self.btnLimparPaciente.setObjectName("btnLimparPaciente")
        self.horizontalLayout.addWidget(self.btnLimparPaciente)
        self.btnPesqPaciente = QtWidgets.QPushButton(PesqTomografias)
        self.btnPesqPaciente.setObjectName("btnPesqPaciente")
        self.horizontalLayout.addWidget(self.btnPesqPaciente)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(PesqTomografias)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edtAluno = QtWidgets.QLineEdit(PesqTomografias)
        self.edtAluno.setEnabled(False)
        self.edtAluno.setObjectName("edtAluno")
        self.horizontalLayout_2.addWidget(self.edtAluno)
        self.btnLimparAluno = QtWidgets.QPushButton(PesqTomografias)
        self.btnLimparAluno.setObjectName("btnLimparAluno")
        self.horizontalLayout_2.addWidget(self.btnLimparAluno)
        self.btnPesqAluno = QtWidgets.QPushButton(PesqTomografias)
        self.btnPesqAluno.setObjectName("btnPesqAluno")
        self.horizontalLayout_2.addWidget(self.btnPesqAluno)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(PesqTomografias)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.btnConfirmar = QtWidgets.QPushButton(PesqTomografias)
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.verticalLayout.addWidget(self.btnConfirmar)
        self.btnCancelar = QtWidgets.QPushButton(PesqTomografias)
        self.btnCancelar.setObjectName("btnCancelar")
        self.verticalLayout.addWidget(self.btnCancelar)

        self.retranslateUi(PesqTomografias)
        QtCore.QMetaObject.connectSlotsByName(PesqTomografias)

    def retranslateUi(self, PesqTomografias):
        _translate = QtCore.QCoreApplication.translate
        PesqTomografias.setWindowTitle(_translate("PesqTomografias", "Dialog"))
        self.label.setText(_translate("PesqTomografias", "Paciente"))
        self.btnLimparPaciente.setText(_translate("PesqTomografias", "Limpar"))
        self.btnPesqPaciente.setText(_translate("PesqTomografias", "Pesquisar"))
        self.label_2.setText(_translate("PesqTomografias", "Aluno"))
        self.btnLimparAluno.setText(_translate("PesqTomografias", "Limpar"))
        self.btnPesqAluno.setText(_translate("PesqTomografias", "Pesquisar"))
        self.btnConfirmar.setText(_translate("PesqTomografias", "&Confirmar"))
        self.btnCancelar.setText(_translate("PesqTomografias", "Cancela&r"))