from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PesqPanoramicas(object):
    def setupUi(self, PesqPanoramicas):
        PesqPanoramicas.setObjectName("PesqPanoramicas")
        PesqPanoramicas.setWindowModality(QtCore.Qt.WindowModal)
        PesqPanoramicas.resize(691, 556)
        self.verticalLayout = QtWidgets.QVBoxLayout(PesqPanoramicas)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(PesqPanoramicas)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.edtPaciente = QtWidgets.QLineEdit(PesqPanoramicas)
        self.edtPaciente.setEnabled(False)
        self.edtPaciente.setObjectName("edtPaciente")
        self.horizontalLayout_4.addWidget(self.edtPaciente)
        self.btnLimparPaciente = QtWidgets.QPushButton(PesqPanoramicas)
        self.btnLimparPaciente.setEnabled(False)
        self.btnLimparPaciente.setObjectName("btnLimparPaciente")
        self.horizontalLayout_4.addWidget(self.btnLimparPaciente)
        self.btnPesqPaciente = QtWidgets.QPushButton(PesqPanoramicas)
        self.btnPesqPaciente.setEnabled(False)
        self.btnPesqPaciente.setObjectName("btnPesqPaciente")
        self.horizontalLayout_4.addWidget(self.btnPesqPaciente)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_2 = QtWidgets.QLabel(PesqPanoramicas)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edtAluno = QtWidgets.QLineEdit(PesqPanoramicas)
        self.edtAluno.setEnabled(False)
        self.edtAluno.setObjectName("edtAluno")
        self.horizontalLayout_3.addWidget(self.edtAluno)
        self.btnLimparAluno = QtWidgets.QPushButton(PesqPanoramicas)
        self.btnLimparAluno.setEnabled(False)
        self.btnLimparAluno.setObjectName("btnLimparAluno")
        self.horizontalLayout_3.addWidget(self.btnLimparAluno)
        self.btnPesqAluno = QtWidgets.QPushButton(PesqPanoramicas)
        self.btnPesqAluno.setEnabled(False)
        self.btnPesqAluno.setObjectName("btnPesqAluno")
        self.horizontalLayout_3.addWidget(self.btnPesqAluno)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableWidget = QtWidgets.QTableWidget(PesqPanoramicas)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.btnConfirmar = QtWidgets.QPushButton(PesqPanoramicas)
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.verticalLayout.addWidget(self.btnConfirmar)
        self.btnCancelar = QtWidgets.QPushButton(PesqPanoramicas)
        self.btnCancelar.setObjectName("btnCancelar")
        self.verticalLayout.addWidget(self.btnCancelar)

        self.retranslateUi(PesqPanoramicas)
        QtCore.QMetaObject.connectSlotsByName(PesqPanoramicas)

    def retranslateUi(self, PesqPanoramicas):
        _translate = QtCore.QCoreApplication.translate
        PesqPanoramicas.setWindowTitle(_translate("PesqPanoramicas", "Dialog"))
        self.label.setText(_translate("PesqPanoramicas", "Paciente"))
        self.btnLimparPaciente.setText(_translate("PesqPanoramicas", "Limpar"))
        self.btnPesqPaciente.setText(_translate("PesqPanoramicas", "Pesquisar"))
        self.label_2.setText(_translate("PesqPanoramicas", "Aluno"))
        self.btnLimparAluno.setText(_translate("PesqPanoramicas", "Limpar"))
        self.btnPesqAluno.setText(_translate("PesqPanoramicas", "Pesquisar"))
        self.btnConfirmar.setText(_translate("PesqPanoramicas", "&Confirmar"))
        self.btnCancelar.setText(_translate("PesqPanoramicas", "Cancela&r"))